name: Reusable Docker Build

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ${{ inputs.service }}:latest ./${{ inputs.service }}